%Test 
msg = 'Error test set default params: ';
pars = set_default_pars_nscs_long_step();
assert(isstruct(pars),msg);

expected_field_names = ...
{'max_iter',...
'max_affine_backtrack_iter',...
'backtrack_affine_constant',...
'eta',...                  
'stop_primal',...
'stop_dual',...
'stop_gap',... 
'stop_mu',...     
'stop_tau_kappa',...
'solve_second_order',...
'print',...                   
'delta',...
'gamma',...
'max_iter_ref_rounds',...
'neigh'};

for j =1:length(expected_field_names)
    assert(isfield(pars,expected_field_names{j}),[msg,expected_field_names{j}])
end

